version: "3.8"
services:

  adminoperations:
    environment:
      ADMINOPERATIONS_HOST: adminoperations
    # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
    #                   -t marketplace --secret id=ca.key,src=ca.key
    image: adminoperations
    networks:
      - microservices
    ports:
      - 5000:5000

  recommendations:
    # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
    #                   -t recommendations --secret id=ca.key,src=ca.key
    image: recommendations
    networks:
      - microservices
  mongo:
    image: mongo
    networks:
      - microservices

networks:
  microservices:
