scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-svc:9090']

  - job_name: usermanagementserversvc
    scrape_interval: 5s
    static_configs:
      - targets: ['usermanagementserversvc:50052']