apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "writedb"
  labels:
    app: "writedb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "writedb"
  template:
    metadata:
      labels:
        app: "writedb"
    spec:
      containers:
        - name: "writedb"
          image: "gcr.io/${PROJECT_ID}/writedb"
          ports:
            - containerPort: 50111