apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementserver-deployment
  labels:
    app: usermanagementserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementserver
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: usermanagementserver
    spec:
      containers:
        - name: usermanagementserver
          image: "gcr.io/${PROJECT_ID}/usermanagementserver"
          args:
            - "--config.file=/prometheus/prometheus-cm.yaml"
          ports:
            - containerPort: 50052
---
kind: Service
apiVersion: v1
metadata:
  name: usermanagementserversvc
spec:
  type: ClusterIP
  selector:
    app: usermanagementserver
  ports:
    - name: server
      protocol: TCP
      port: 50052
      targetPort: 50052
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementapi"
  labels:
    app: "usermanagementapi"
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  selector:
    matchLabels:
      app: "usermanagementapi"
  template:
    metadata:
      labels:
        app: "usermanagementapi"
    spec:
      containers:
        - name: "usermanagementapi"
          image: "gcr.io/${PROJECT_ID}/usermanagementapi"
          ports:
            - containerPort: 5004
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "usermanagementapi"
spec:
  selector:
    app: "usermanagementapi"
  ports:
    - name: "api"
      port: 5004
      targetPort: 5004
  type: LoadBalancer