apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "adminoperationsserver"
  labels:
    app: "adminoperationsserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminoperationsserver"
  template:
    metadata:
      labels:
        app: "adminoperationsserver"
    spec:
      containers:
        - name: "adminoperationsserver"
          image: "gcr.io/${VAR:PROJECT_ID}/adminoperationsserver"
          ports:
            - containerPort: 50051
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "adminoperationsapi"
  labels:
    app: "adminoperationsapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminoperationsapi"
  template:
    metadata:
      labels:
        app: "adminoperationsapi"
    spec:
      containers:
        - name: "adminoperationsapi"
          image: "gcr.io/${VAR:PROJECT_ID}/adminoperationsapi"
          ports:
            - containerPort: 5003
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementserver"
  labels:
    app: "usermanagementserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "usermanagementserver"
  template:
    metadata:
      labels:
        app: "usermanagementserver"
    spec:
      containers:
        - name: "usermanagementserver"
          image: "gcr.io/${VAR:PROJECT_ID}/usermanagementserver"
          ports:
            - containerPort: 50052
---
apiVersion: "apps/v1"
kind: Service
metadata:
  name: "usermanagementapi"
spec:
  selector:
    app: "usermanagementapi"
  ports:
    - name: api
    port: 5004
    targetPort: 5004
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementapi"
  labels:
    app: "usermanagementapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "usermanagementapi"
  template:
    metadata:
      labels:
        app: "usermanagementapi"
    spec:
      containers:
        - name: "usermanagementapi"
          image: "gcr.io/${VAR:PROJECT_ID}/usermanagementapi"
          ports:
            - containerPort: 5004