apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "adminoperationsserver"
  labels:
    app: "adminoperationsserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminoperationsserver"
  template:
    metadata:
      labels:
        app: "adminoperationsserver"
    spec:
      containers:
        - name: "adminoperationsserver"
          image: "gcr.io/copper-mender-345714/adminoperationsserver"
          ports:
            - containerPort: 50051
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "adminoperationsapi"
  labels:
    app: "adminoperationsapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminoperationsapi"
  template:
    metadata:
      labels:
        app: "adminoperationsapi"
    spec:
      containers:
        - name: "adminoperationsapi"
          image: "gcr.io/copper-mender-345714/adminoperationsapi"
          ports:
            - containerPort: 5003
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementserver"
  labels:
    app: "usermanagementserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "usermanagementserver"
  template:
    metadata:
      labels:
        app: "usermanagementserver"
    spec:
      containers:
        - name: "usermanagementserver"
          image: "gcr.io/copper-mender-345714/usermanagementserver"
          ports:
            - containerPort: 50052
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementapi"
  labels:
    app: "usermanagementapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "usermanagementapi"
  template:
    metadata:
      labels:
        app: "usermanagementapi"
    spec:
      containers:
        - name: "usermanagementapi"
          image: "gcr.io/copper-mender-345714/usermanagementapi"
          ports:
            - containerPort: 5004
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "libraryserver"
  labels:
    app: "libraryserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "libraryserver"
  template:
    metadata:
      labels:
        app: "libraryserver"
    spec:
      containers:
        - name: "libraryserver"
          image: "gcr.io/phase4-cn/libraryserver"
          ports:
            - containerPort: 50053
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "libraryapi"
  labels:
    app: "libraryapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "libraryapi"
  template:
    metadata:
      labels:
        app: "libraryapi"
    spec:
      containers:
        - name: "libraryapi"
          image: "gcr.io/phase4-cn/libraryapi"
          ports:
            - containerPort: 5001
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "wishlistserver"
  labels:
    app: "wishlistserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wishlistserver"
  template:
    metadata:
      labels:
        app: "wishlistserver"
    spec:
      containers:
        - name: "wishlistserver"
          image: "gcr.io/phase4-cn/wishlistserver"
          ports:
            - containerPort: 50058
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "wishlistapi"
  labels:
    app: "wishlistapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wishlistapi"
  template:
    metadata:
      labels:
        app: "wishlistapi"
    spec:
      containers:
        - name: "wishlistapi"
          image: "gcr.io/phase4-cn/wishlistapi"
          ports:
            - containerPort: 5002