apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "adminoperationsserver"
  labels:
    app: "adminoperationsserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminoperationsserver"
  template:
    metadata:
      labels:
        app: "adminoperationsserver"
    spec:
      containers:
        - name: "adminoperationsserver"
          image: "gcr.io/${PROJECT_ID}/adminoperationsserver"
          ports:
            - containerPort: 50051
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "adminoperationsserver"
spec:
  selector:
    app: "adminoperationsserver"
  ports:
    - name: "server"
      port: 50051
      targetPort: 50051
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "adminoperationsapi"
  labels:
    app: "adminoperationsapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminoperationsapi"
  template:
    metadata:
      labels:
        app: "adminoperationsapi"
    spec:
      containers:
        - name: "adminoperationsapi"
          image: "gcr.io/${PROJECT_ID}/adminoperationsapi"
          ports:
            - containerPort: 5003
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "adminoperationsapi"
spec:
  selector:
    app: "adminoperationsapi"
  ports:
    - name: "api"
      port: 5003
      targetPort: 5003
  type: LoadBalancer
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementserver"
  labels:
    app: "usermanagementserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "usermanagementserver"
  template:
    metadata:
      labels:
        app: "usermanagementserver"
    spec:
      containers:
        - name: "usermanagementserver"
          image: "gcr.io/${PROJECT_ID}/usermanagementserver"
          ports:
            - containerPort: 50052
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "usermanagementserver"
spec:
  selector:
    app: "usermanagementserver"
  ports:
    - name: "server"
      port: 50052
      targetPort: 50052
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "usermanagementapi"
  labels:
    app: "usermanagementapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "usermanagementapi"
  template:
    metadata:
      labels:
        app: "usermanagementapi"
    spec:
      containers:
        - name: "usermanagementapi"
          image: "gcr.io/${PROJECT_ID}/usermanagementapi"
          ports:
            - containerPort: 5004
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "usermanagementapi"
spec:
  selector:
    app: "usermanagementapi"
  ports:
    - name: "api"
      port: 5004
      targetPort: 5004
  type: LoadBalancer
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "libraryserver"
  labels:
    app: "libraryserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "libraryserver"
  template:
    metadata:
      labels:
        app: "libraryserver"
    spec:
      containers:
        - name: "libraryserver"
          image: "gcr.io/${PROJECT_ID}/libraryserver"
          ports:
            - containerPort: 50053
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "libraryserver"
spec:
  selector:
    app: "libraryserver"
  ports:
    - name: "server"
      port: 50053
      targetPort: 50053
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "libraryapi"
  labels:
    app: "libraryapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "libraryapi"
  template:
    metadata:
      labels:
        app: "libraryapi"
    spec:
      containers:
        - name: "libraryapi"
          image: "gcr.io/${PROJECT_ID}/libraryapi"
          ports:
            - containerPort: 5001
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "libraryapi"
spec:
  selector:
    app: "libraryapi"
  ports:
    - name: "api"
      port: 5001
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "wishlistserver"
  labels:
    app: "wishlistserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wishlistserver"
  template:
    metadata:
      labels:
        app: "wishlistserver"
    spec:
      containers:
        - name: "wishlistserver"
          image: "gcr.io/${PROJECT_ID}/wishlistserver"
          ports:
            - containerPort: 50058
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "wishlistserver"
spec:
  selector:
    app: "wishlistserver"
  ports:
    - name: "server"
      port: 50058
      targetPort: 50058
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "wishlistapi"
  labels:
    app: "wishlistapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wishlistapi"
  template:
    metadata:
      labels:
        app: "wishlistapi"
    spec:
      containers:
        - name: "wishlistapi"
          image: "gcr.io/${PROJECT_ID}/wishlistapi"
          ports:
            - containerPort: 5002
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "wishlistapi"
spec:
  selector:
    app: "wishlistapi"
  ports:
    - name: "api"
      port: 5002
      targetPort: 5002
  type: LoadBalancer
---